# Generated by Django 3.2.4 on 2022-05-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220522_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaId',
            new_name='categoria',
        ),
    ]
