# Generated by Django 3.2.4 on 2022-05-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_categoriaid_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='facturaId',
            new_name='factura',
        ),
        migrations.RenameField(
            model_name='detalle',
            old_name='productoId',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='clienteId',
            new_name='cliente',
        ),
    ]
