# Generated by Django 3.2.4 on 2022-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220524_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechaFactura',
            field=models.DateField(auto_now_add=True),
        ),
    ]
